// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: rezoagwe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapAction int32

const (
	BootstrapAction_DISCOVER BootstrapAction = 0
	BootstrapAction_REGISTER BootstrapAction = 1
)

// Enum value maps for BootstrapAction.
var (
	BootstrapAction_name = map[int32]string{
		0: "DISCOVER",
		1: "REGISTER",
	}
	BootstrapAction_value = map[string]int32{
		"DISCOVER": 0,
		"REGISTER": 1,
	}
)

func (x BootstrapAction) Enum() *BootstrapAction {
	p := new(BootstrapAction)
	*p = x
	return p
}

func (x BootstrapAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BootstrapAction) Descriptor() protoreflect.EnumDescriptor {
	return file_rezoagwe_proto_enumTypes[0].Descriptor()
}

func (BootstrapAction) Type() protoreflect.EnumType {
	return &file_rezoagwe_proto_enumTypes[0]
}

func (x BootstrapAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BootstrapAction.Descriptor instead.
func (BootstrapAction) EnumDescriptor() ([]byte, []int) {
	return file_rezoagwe_proto_rawDescGZIP(), []int{0}
}

type DiscoveryAction int32

const (
	DiscoveryAction_SET    DiscoveryAction = 0
	DiscoveryAction_DELETE DiscoveryAction = 1
)

// Enum value maps for DiscoveryAction.
var (
	DiscoveryAction_name = map[int32]string{
		0: "SET",
		1: "DELETE",
	}
	DiscoveryAction_value = map[string]int32{
		"SET":    0,
		"DELETE": 1,
	}
)

func (x DiscoveryAction) Enum() *DiscoveryAction {
	p := new(DiscoveryAction)
	*p = x
	return p
}

func (x DiscoveryAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryAction) Descriptor() protoreflect.EnumDescriptor {
	return file_rezoagwe_proto_enumTypes[1].Descriptor()
}

func (DiscoveryAction) Type() protoreflect.EnumType {
	return &file_rezoagwe_proto_enumTypes[1]
}

func (x DiscoveryAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryAction.Descriptor instead.
func (DiscoveryAction) EnumDescriptor() ([]byte, []int) {
	return file_rezoagwe_proto_rawDescGZIP(), []int{1}
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_rezoagwe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_rezoagwe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_rezoagwe_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type BootstrapMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action BootstrapAction `protobuf:"varint,1,opt,name=action,proto3,enum=rezoagwe.BootstrapAction" json:"action,omitempty"`
	Host   *Host           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *BootstrapMessage) Reset() {
	*x = BootstrapMessage{}
	mi := &file_rezoagwe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapMessage) ProtoMessage() {}

func (x *BootstrapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rezoagwe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapMessage.ProtoReflect.Descriptor instead.
func (*BootstrapMessage) Descriptor() ([]byte, []int) {
	return file_rezoagwe_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapMessage) GetAction() BootstrapAction {
	if x != nil {
		return x.Action
	}
	return BootstrapAction_DISCOVER
}

func (x *BootstrapMessage) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string          `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value  []byte          `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Hosts  []*Host         `protobuf:"bytes,3,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Action DiscoveryAction `protobuf:"varint,4,opt,name=action,proto3,enum=rezoagwe.DiscoveryAction" json:"action,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_rezoagwe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_rezoagwe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_rezoagwe_proto_rawDescGZIP(), []int{2}
}

func (x *Payload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Payload) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Payload) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Payload) GetAction() DiscoveryAction {
	if x != nil {
		return x.Action
	}
	return DiscoveryAction_SET
}

var File_rezoagwe_proto protoreflect.FileDescriptor

var file_rezoagwe_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x72, 0x65, 0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x69, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x7a,
	0x6f, 0x61, 0x67, 0x77, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65,
	0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x22, 0x8a, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x65,
	0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x2d,
	0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x2a, 0x26, 0x0a,
	0x0f, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x10, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x72, 0x69, 0x6f, 0x74, 0x2f, 0x72, 0x65,
	0x7a, 0x6f, 0x61, 0x67, 0x77, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rezoagwe_proto_rawDescOnce sync.Once
	file_rezoagwe_proto_rawDescData = file_rezoagwe_proto_rawDesc
)

func file_rezoagwe_proto_rawDescGZIP() []byte {
	file_rezoagwe_proto_rawDescOnce.Do(func() {
		file_rezoagwe_proto_rawDescData = protoimpl.X.CompressGZIP(file_rezoagwe_proto_rawDescData)
	})
	return file_rezoagwe_proto_rawDescData
}

var file_rezoagwe_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rezoagwe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rezoagwe_proto_goTypes = []any{
	(BootstrapAction)(0),     // 0: rezoagwe.BootstrapAction
	(DiscoveryAction)(0),     // 1: rezoagwe.DiscoveryAction
	(*Host)(nil),             // 2: rezoagwe.Host
	(*BootstrapMessage)(nil), // 3: rezoagwe.BootstrapMessage
	(*Payload)(nil),          // 4: rezoagwe.Payload
}
var file_rezoagwe_proto_depIdxs = []int32{
	0, // 0: rezoagwe.BootstrapMessage.action:type_name -> rezoagwe.BootstrapAction
	2, // 1: rezoagwe.BootstrapMessage.host:type_name -> rezoagwe.Host
	2, // 2: rezoagwe.Payload.hosts:type_name -> rezoagwe.Host
	1, // 3: rezoagwe.Payload.action:type_name -> rezoagwe.DiscoveryAction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rezoagwe_proto_init() }
func file_rezoagwe_proto_init() {
	if File_rezoagwe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rezoagwe_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rezoagwe_proto_goTypes,
		DependencyIndexes: file_rezoagwe_proto_depIdxs,
		EnumInfos:         file_rezoagwe_proto_enumTypes,
		MessageInfos:      file_rezoagwe_proto_msgTypes,
	}.Build()
	File_rezoagwe_proto = out.File
	file_rezoagwe_proto_rawDesc = nil
	file_rezoagwe_proto_goTypes = nil
	file_rezoagwe_proto_depIdxs = nil
}
