// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rezoagwe.proto

package rezoagwe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BootstrapAction int32

const (
	BootstrapAction_DISCOVER BootstrapAction = 0
	BootstrapAction_REGISTER BootstrapAction = 1
)

var BootstrapAction_name = map[int32]string{
	0: "DISCOVER",
	1: "REGISTER",
}

var BootstrapAction_value = map[string]int32{
	"DISCOVER": 0,
	"REGISTER": 1,
}

func (x BootstrapAction) String() string {
	return proto.EnumName(BootstrapAction_name, int32(x))
}

func (BootstrapAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a6de26c59e6c45c, []int{0}
}

type Host struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6de26c59e6c45c, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type BootstrapMessage struct {
	Action               BootstrapAction `protobuf:"varint,1,opt,name=action,proto3,enum=rezoagwe.BootstrapAction" json:"action,omitempty"`
	Host                 *Host           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BootstrapMessage) Reset()         { *m = BootstrapMessage{} }
func (m *BootstrapMessage) String() string { return proto.CompactTextString(m) }
func (*BootstrapMessage) ProtoMessage()    {}
func (*BootstrapMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6de26c59e6c45c, []int{1}
}

func (m *BootstrapMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapMessage.Unmarshal(m, b)
}
func (m *BootstrapMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapMessage.Marshal(b, m, deterministic)
}
func (m *BootstrapMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapMessage.Merge(m, src)
}
func (m *BootstrapMessage) XXX_Size() int {
	return xxx_messageInfo_BootstrapMessage.Size(m)
}
func (m *BootstrapMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapMessage proto.InternalMessageInfo

func (m *BootstrapMessage) GetAction() BootstrapAction {
	if m != nil {
		return m.Action
	}
	return BootstrapAction_DISCOVER
}

func (m *BootstrapMessage) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

type Payload struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Hosts                []*Host  `protobuf:"bytes,3,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6de26c59e6c45c, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Payload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func init() {
	proto.RegisterEnum("rezoagwe.BootstrapAction", BootstrapAction_name, BootstrapAction_value)
	proto.RegisterType((*Host)(nil), "rezoagwe.Host")
	proto.RegisterType((*BootstrapMessage)(nil), "rezoagwe.BootstrapMessage")
	proto.RegisterType((*Payload)(nil), "rezoagwe.Payload")
}

func init() {
	proto.RegisterFile("rezoagwe.proto", fileDescriptor_6a6de26c59e6c45c)
}

var fileDescriptor_6a6de26c59e6c45c = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0xad, 0xca,
	0x4f, 0x4c, 0x2f, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xa4,
	0xb8, 0x58, 0x3c, 0xf2, 0x8b, 0x4b, 0x84, 0x84, 0x20, 0xb4, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x98, 0xad, 0x94, 0xc9, 0x25, 0xe0, 0x94, 0x9f, 0x5f, 0x52, 0x5c, 0x52, 0x94, 0x58, 0xe0,
	0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x64, 0xc8, 0xc5, 0x96, 0x98, 0x5c, 0x92, 0x99, 0x9f,
	0x07, 0x56, 0xc9, 0x67, 0x24, 0xa9, 0x07, 0x37, 0x1a, 0xae, 0xd6, 0x11, 0xac, 0x20, 0x08, 0xaa,
	0x50, 0x48, 0x89, 0x8b, 0x25, 0x03, 0x64, 0x34, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x1f, 0x42,
	0x03, 0xc8, 0x92, 0x20, 0xb0, 0x9c, 0x52, 0x38, 0x17, 0x7b, 0x40, 0x62, 0x65, 0x4e, 0x7e, 0x62,
	0x8a, 0x90, 0x00, 0x17, 0xb3, 0x77, 0x6a, 0x25, 0xd4, 0x21, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b,
	0x58, 0x62, 0x4e, 0x69, 0x2a, 0xd8, 0x04, 0x9e, 0x20, 0x08, 0x47, 0x48, 0x85, 0x8b, 0x15, 0xa4,
	0xb5, 0x58, 0x82, 0x59, 0x81, 0x19, 0x8b, 0xb9, 0x10, 0x49, 0x2d, 0x5d, 0x2e, 0x7e, 0x34, 0x77,
	0x09, 0xf1, 0x70, 0x71, 0xb8, 0x78, 0x06, 0x3b, 0xfb, 0x87, 0xb9, 0x06, 0x09, 0x30, 0x80, 0x78,
	0x41, 0xae, 0xee, 0x9e, 0xc1, 0x21, 0xae, 0x41, 0x02, 0x8c, 0x49, 0x6c, 0xe0, 0xf0, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xb2, 0xeb, 0x97, 0x31, 0x01, 0x00, 0x00,
}
